✨  Adding leads apis
Candid-Maven/education-directory-net-backend pull request #11
Opened 2023-05-23 19:08 UTC by Nabeel-Akhtar

1. Leads Api
2. Models for Leads
3. Create Lead Api
4. Defining Urls

2023-05-24 07:35 UTC, tasawernawaz requested changes
- Make sure we are using correct fields types.
- Use serializer
- I can see only create api, what other endpoints we are expecting from this PR.

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    ip = models.TextField()
can we use `GenericIPAddressField`?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    web_url = models.TextField()
https://docs.djangoproject.com/en/4.2/ref/models/fields/#urlfield

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    web_session_id = models.TextField()
are we expecting a text based id?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    tcpa_timestamp_marketing = models.TextField()
can we use datetime field here?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    ad_id = models.TextField()
same here, are we expecting text based IDs?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    traffic_trusted_form_url = models.TextField()
URLField?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    traffic_jornaya_lead_id = models.TextField()
Integer or Text?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    email = models.TextField()
Email field?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/models.py
> +    age = models.TextField()
Integer?

2023-05-24 07:35 UTC, tasawernawaz commented on leads/views.py
> +    return Response("Lead created successfully.", status=200)
create serializers for these models and use them to serialize and de serialize objects.

2023-05-24 17:50 UTC, Nabeel-Akhtar commented on leads/models.py
> +    traffic_jornaya_lead_id = models.TextField()
traffic_jornaya_lead_id = models.TextField()

Text

2023-05-24 17:55 UTC, Nabeel-Akhtar commented on leads/views.py
> +    return Response("Lead created successfully.", status=200)
Updated. Will be reflect in the new commmit

2023-05-24 17:56 UTC, Nabeel-Akhtar commented on leads/models.py
> +    age = models.TextField()
By mistake. Updated (Age)

2023-05-24 17:57 UTC, Nabeel-Akhtar commented on leads/models.py
> +    email = models.TextField()
that is expected to be like this. Refer to the ERD

2023-05-24 17:58 UTC, Nabeel-Akhtar commented on leads/models.py
> +    gender = models.TextField()
that is expected to be like this. Refer to the ERD

2023-05-24 17:58 UTC, Nabeel-Akhtar commented on leads/models.py
> +    traffic_trusted_form_url = models.TextField()
that is expected to be like this. Refer to the ERD

2023-05-24 17:59 UTC, Nabeel-Akhtar commented on leads/models.py
> +    ad_id = models.TextField()
that is expected to be like this. Refer to the ERD

2023-05-24 17:59 UTC, Nabeel-Akhtar commented on leads/models.py
> +    tcpa_timestamp_marketing = models.TextField()
that is expected to be like this. Refer to the ERD

2023-05-24 17:59 UTC, Nabeel-Akhtar commented on leads/models.py
> +    web_session_id = models.TextField()
that is expected to be like this because token id can have string values

2023-05-24 18:01 UTC, Nabeel-Akhtar commented on leads/models.py
> +    ip = models.TextField()
we can discuss on it

2023-05-24 18:01 UTC, Nabeel-Akhtar commented on leads/models.py
> +    web_url = models.TextField()
we can discuss on it

2023-05-30 04:20 UTC, tasawernawaz commented on leads/test_data.py
please create a new folder `fixtures` and save this as a json file.

2023-05-30 04:30 UTC, tasawernawaz requested changes

2023-05-30 04:30 UTC, tasawernawaz commented on leads/views.py
> +        print("DATA: ", data)
remove this.

2023-05-30 04:30 UTC, tasawernawaz commented on leads/views.py
> +    except Exception as e:
hmm, this might not be useful as much we want, this wont tell us whats wrong. We need to handle specific exceptions.

2023-05-30 04:30 UTC, tasawernawaz commented on leads/views.py
> +        return Response("Lead not found.", status=404)
if you can use [ModelViewSet](https://www.django-rest-framework.org/api-guide/viewsets/#modelviewset) this code can be eliminated, just override the requirement methods and add [custom actions](https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing) for custom routes. e.g `/end_session`

2023-05-30 04:30 UTC, tasawernawaz commented on leads/test_data.py
I can't see any usage of this file?

2023-05-30 04:30 UTC, tasawernawaz commented on leads/views.py
> +def create_lead(request):
this should be a atomic operation, if anything goes wrong in one model, everything related to that lead should get reverted. https://docs.djangoproject.com/en/4.2/topics/db/transactions/#controlling-transactions-explicitly

2023-05-30 04:30 UTC, tasawernawaz commented on leads/views.py
> +        return Response("Lead created successfully.", status=200)
Ideally, we should use nested serialize to validate everything at once.

2023-05-30 04:42 UTC, tasawernawaz commented
also, since build is failing, please install `isort` and `black` so we can use consistent formatting.

2023-06-02 04:35 UTC, tasawernawaz requested changes
@Nabeel-Akhtar I have added few more suggestions.

2023-06-02 04:35 UTC, tasawernawaz commented on leads/session_end_job.py
> +        print("Session ended successfully.")
instead of print, use stdout, as this is going to run as a cron job.

2023-06-02 04:35 UTC, tasawernawaz commented on leads/session_end_job.py
can you write this as a management command. https://docs.djangoproject.com/en/4.2/howto/custom-management-commands/

2023-06-02 04:35 UTC, tasawernawaz commented on leads/test_data.py
i can see any usage of this file, can we move this to `/fixtures`

2023-06-02 04:35 UTC, tasawernawaz commented on leads/urls.py
> +    path('lead/<int:lead_id>/', get_lead_detail, name='lead-detail'),
why we need `lead` here, our base url is `leads` so a single lead should be available at `/leads/<id>` not at `leads/lead/<id>`

2023-06-02 04:35 UTC, tasawernawaz commented on leads/urls.py
> +    path('filter/', filter_lead, name='filter_lead'),
for consistency use name with hyphen e.g `filter-lead`

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +        return Response("Lead not found.", status=404)
move this code out of try block
```
serializer = LeadSerializer(lead)
        return Response(serializer.data)
```
otherwise, any error while serializing would be caught as DoesNotExist

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +        lead = Lead.objects.get(id=lead_id)
why don't we try https://docs.djangoproject.com/en/4.2/topics/http/shortcuts/#get-object-or-404

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +                return Response({'error': 'Lead not found'}, status=404)
https://docs.djangoproject.com/en/4.2/topics/http/shortcuts/#get-object-or-404

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +        return Response("Lead created successfully.", status=200)
This response can have a little more details, like we have created and what we can't if there is any error, since we are doing a lot of stuff in this view.

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +
https://docs.djangoproject.com/en/4.2/topics/http/shortcuts/#get-object-or-404

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +
https://docs.djangoproject.com/en/4.2/topics/http/shortcuts/#get-object-or-404

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +            # leads = Lead.objects.filter(created_at=data['date'])
if we don't need this remove this line.

2023-06-02 04:35 UTC, tasawernawaz commented on leads/views.py
> +            # leads = Lead.objects.filter(created_at=data['date'])
can we apply more that one filter at a time? if yes, then that's not handled.

2023-06-02 04:36 UTC, tasawernawaz commented
@Nabeel-Akhtar this is still pending

> also, since build is failing, please install isort and black so we can use consistent formatting.

One more general suggestion, one PR should create one migration/app. You can delete these migrations and create a single file.

2023-08-09 20:11 UTC, closed without merging

2023-08-09 20:12 UTC, csaument commented
Closed stale PR.