Feat: Adds a Post model with routes and controllers.
Candid-Maven/education-directory-net-backend pull request #12
Opened 2023-06-01 01:00 UTC by csaument

- feat: Add posts table, routes, controllers, and seed data migration
- feat: adds posts model
- model and controller updates for posts
- fix: allows unique slug generation by moving logic from model to view.

2023-06-01 16:43 UTC, tasawernawaz requested changes

2023-06-01 16:43 UTC, tasawernawaz commented on education_directory/settings.py
> +from dotenv import load_dotenv
why are we changing this to load_dotenv?

2023-06-01 16:43 UTC, tasawernawaz commented on education_directory/settings.py
> +#     AWS_QUERYSTRING_AUTH = False
this was useful to test upload images on the local machine.

2023-06-01 16:43 UTC, tasawernawaz commented on api/views.py
> +    def _get_unique_slug(self, requested_slug, category):
move this to models for consistency.

2023-06-01 16:43 UTC, tasawernawaz commented on api/views.py
> +    def validate_image(self, value):
validation should be done at serializer or models level.

2023-06-01 16:43 UTC, tasawernawaz commented on api/views.py
> +        request.data["image"] = validated_image
we can use the patch method for such partial updates.

2023-06-01 16:43 UTC, tasawernawaz commented on api/views.py
> +    def retrieve(self, request, *args, **kwargs):
why are we overriding this method?

2023-06-01 16:43 UTC, tasawernawaz commented on api/views.py
> +    def create(self, request, *args, **kwargs):
same here, we don't need to override this method.

2023-06-01 16:43 UTC, tasawernawaz commented on api/views.py
> +from rest_framework.pagination import PageNumberPagination
all imports should be at the top of the file.

2023-06-01 16:43 UTC, tasawernawaz commented on api/migrations/0032_auto_20230523_0308.py
in a single PR, ideally, there should be only one migration/app. You can delete both of these migrations and create one.

2023-06-01 16:43 UTC, tasawernawaz commented on .env example
> -AWS_S3_REGION_NAME=
why are we removing this file, this was useful for new developers, they can start from these vars.

2023-06-01 20:35 UTC, csaument commented on education_directory/settings.py
> +from dotenv import load_dotenv
Loaded secrets.env for local testing. Not necessary for deployment.

2023-06-01 20:38 UTC, csaument commented on education_directory/settings.py
> +#     AWS_QUERYSTRING_AUTH = False
Disabled AWS connectivity to test the database on local machine. This section can be reverted for deployment.

2023-06-01 20:41 UTC, csaument commented on api/views.py
> +    def _get_unique_slug(self, requested_slug, category):
_get_unique_slug() failed to function in the model; however, it performed correctly in the controller. The model rejected the post/create requests due to unique=True before processing the method with the save() method.

2023-06-01 20:42 UTC, csaument commented on api/views.py
> +    def validate_image(self, value):
The purpose of this method is to determine whether the submitted image exists in the Asset model and process accordingly. Recommend renaming to check_image and maintaining in the controller.

2023-06-01 20:54 UTC, csaument commented on api/views.py
> +    def retrieve(self, request, *args, **kwargs):
Default behavior reads a post by pk/id. This overrides default behavior to read posts by slug.

2023-06-01 20:57 UTC, csaument commented on api/views.py
> +    def create(self, request, *args, **kwargs):
This overrides default behavior to check whether the asset exists or needs to be created and creates a unique slug for the post entry.

2023-06-01 20:58 UTC, csaument commented on api/views.py
> +from rest_framework.pagination import PageNumberPagination
Fixed.

2023-06-01 20:59 UTC, csaument commented on api/migrations/0032_auto_20230523_0308.py
This migration provided seed data and is functionally unnecessary. Removed file.

2023-06-01 21:00 UTC, csaument commented on .env example
> -AWS_S3_REGION_NAME=
File was renamed to create secrets.env. Recommend keeping with main branch.

2023-06-01 21:03 UTC, csaument commented
Responded to comments/change requests and implemented several changes into origin/feat-blog-posts.

2023-06-01 22:05 UTC, csaument commented on api/views.py
> +        request.data["image"] = validated_image
Updated.

2023-06-01 22:20 UTC, csaument commented on education_directory/settings.py
> +from dotenv import load_dotenv
Reverted file from main branch for deployment.

2023-06-01 22:20 UTC, csaument commented on education_directory/settings.py
> +#     AWS_QUERYSTRING_AUTH = False
Reverted file from main branch for deployment.

2023-06-02 03:51 UTC, tasawernawaz commented on education_directory/settings.py
> +#     AWS_QUERYSTRING_AUTH = False
for development, you can create a .env file and place your secrets there. .env is already added in .gitignore, so it won't be tracked.

2023-06-02 03:52 UTC, tasawernawaz commented on api/views.py
> +    def _get_unique_slug(self, requested_slug, category):
I see, you can move this to serializers then.

2023-06-02 03:54 UTC, tasawernawaz commented on api/views.py
> +    def retrieve(self, request, *args, **kwargs):
This `post_slug_detail = PostViewSet.as_view(DETAIL_DICT, lookup_field="slug")` should allow retrieval via slug. No need to override this.

2023-06-02 03:55 UTC, tasawernawaz commented on api/views.py
> +    def create(self, request, *args, **kwargs):
ideally, this can be done in serializer and/or model manager.

2023-06-02 03:58 UTC, tasawernawaz commented on api/views.py
> +        except ValueError:
```suggestion
        try:
            value = int(value)  # Convert the string to an integer
            asset = Asset.objects.get(id=value)
            return asset.pk
        except ObjectDoesNotExist:
```

2023-06-02 04:04 UTC, tasawernawaz commented on api/views.py
> +        return slug
```suggestion
        while Post.objects.filter(slug=slug).exists():
            slug = f"{slug}-{count}"
            count += 1

        return slug
```

2023-06-02 14:50 UTC, csaument commented on api/views.py
> +        return slug
The original logic appends '-{int}' to each iteration. This can result in '-1-1-1' for certain edge cases.

For example, if a new slug request includes a number that already exists in the database, then it appends '-1' to that requested slug. The more complicated logic handles the edge case where a slug request already includes an appended integer.

2023-06-03 07:41 UTC, tasawernawaz commented on .env example
> -AWS_S3_REGION_NAME=
you can create `.env` instead of `secrets.env` for local development.

2023-06-03 07:54 UTC, tasawernawaz requested changes
Thanks for incorporating the feedback, few minor comments then we can merge this.

2023-06-03 07:54 UTC, tasawernawaz commented on .env example
> -AWS_S3_REGION_NAME=
add a blank line at the end of file.

2023-06-03 07:54 UTC, tasawernawaz commented on api/views.py
> +    def retrieve(self, request, *args, **kwargs):
@csaument did you get a chance to test this?

2023-06-03 07:54 UTC, tasawernawaz commented on api/views.py
> +            request.data.get("slug"), request.data.get("category")
we should provide `title` which would be more unique and readable slug instead of `category`.

2023-06-03 07:54 UTC, tasawernawaz commented on api/views.py
> +        return slug
hmm, lets keep it as it is. Just change `category` to `title`.

2023-07-26 22:14 UTC, csaument commented
Closing PR for old/unused feature.

2023-07-26 22:14 UTC, closed without merging